### ISSUE TITLE
Code can't run in win10/ubuntu18

### ISSUE THREAD

**Issue by shliujing** [smallcowbaby/OmniAnomaly#36]
Hello, running your code, we encountered a lot of problems that have not been resolved yet. The details are as follows:

1. TensorFlow version problem that the library cannot be found. I follow requestments.txt install the dependent libraries. The problem looks like TFSnippet problem? I also tried to install a different version of TFSnippet, but still couldn't fix the problem.

Environmental information:
- win10
- cudn10.0/cudnn11.1
- RTX 3070
- conda python3.6
- requestments.txt(including branch of matser and dependabot/pip/tensorflow-gpu-2.4.0)

Errors message: 

```
$ python main.py
2021-04-17 13:55:52.732294: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from tfsnippet.examples.utils import MLResults, print_with_title
  File "C:\Users\LIU\anaconda3\envs\OmniAnomaly2\lib\site-packages\tfsnippet\__init__.py", line 4, in <module>
    from . import (dataflows, datasets, distributions, layers, ops,
  File "C:\Users\LIU\anaconda3\envs\OmniAnomaly2\lib\site-packages\tfsnippet\dataflows\__init__.py", line 1, in <module>
    from .array_flow import *
  File "C:\Users\LIU\anaconda3\envs\OmniAnomaly2\lib\site-packages\tfsnippet\dataflows\array_flow.py", line 4, in <module>
    from tfsnippet.utils import minibatch_slices_iterator
  File "C:\Users\LIU\anaconda3\envs\OmniAnomaly2\lib\site-packages\tfsnippet\utils\__init__.py", line 17, in <module>
    from .session import *
  File "C:\Users\LIU\anaconda3\envs\OmniAnomaly2\lib\site-packages\tfsnippet\utils\session.py", line 71, in <module>
    def get_variables_as_dict(scope=None, collection=tf.GraphKeys.GLOBAL_VARIABLES):
AttributeError: module 'tensorflow' has no attribute 'GraphKeys'

```

of course, there are some small problems we have solved during the process.

2. Then I switching different graphics cards environment hope to solve the problem. However it happen some new problem.

Environmental information:

- ubuntu
- cudn10.2
- RTX 2080 TI
- conda python3.6
- requestments.txt(in branch of matser)

Errors message: 

```
$ python main.py 
Traceback (most recent call last):
  File "/home/jingliu/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/jingliu/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/jingliu/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/nsai/anaconda3/envs/lj_dl/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/nsai/anaconda3/envs/lj_dl/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    import tensorflow as tf
  File "/home/jingliu/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/jingliu/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/jingliu/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/jingliu/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/jingliu/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/jingliu/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/nsai/anaconda3/envs/lj_dl/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/nsai/anaconda3/envs/lj_dl/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

In branch of dependabot/pip/tensorflow-gpu-2.4.0, after executing pip install -r requestments：

```
INFO: pip is looking at multiple versions of zhusuan to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of tfsnippet to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 11), -r requirements.txt (line 13), -r requirements.txt (line 14), -r requirements.txt (line 7) and six==1.11.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested six==1.11.0
    tfsnippet 0.2.0a1 depends on six>=1.11.0
    zhusuan 0.4.0 depends on six
    fs 2.3.0 depends on six~=1.10
    tensorflow-gpu 2.4.0 depends on six~=1.15.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```
3. In a word, we spent a lot of time running your code and it failed.
is it convenient for you to provide the running environment of **docker version**? What's your hardware conditions and information like CUDN that you can run?

**Comment by shliujing** [comment]
Waiting for your reply

**Comment by shliujing** [comment]
By the way, we've reappearced the comparison with the NASA's paper, only your code **keeps failing**

**Comment by shliujing** [comment]
By the way, we've recurrenced the comparison with the NASA's paper, only your code keeps failing

**Comment by KINGZDong** [comment]
用TensorFlow1.0版本的能跑，2.0的就会有你说的问题
