### ISSUE TITLE
ValueError: Input tensor enters the loop with shape (?, 3, 1), but has shape (?, 3, ?) after one iteration.

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [smallcowbaby/OmniAnomaly#5]
I got this error while using SMAP dataset 
```
Instructions for updating:
Use keras.layers.dense instead.
Traceback (most recent call last):
  File "main.py", line 213, in <module>
    main()
  File "main.py", line 110, in main
    valid_step_freq=config.valid_step_freq)
  File "/media/harry/harry/ML/LSTM/OmniAnomaly/omni_anomaly/training.py", line 121, in __init__
    x=self._input_x, n_z=n_z)
  File "/media/harry/harry/ML/LSTM/OmniAnomaly/omni_anomaly/model.py", line 138, in get_training_loss
    chain = self.vae.chain(x, n_z=n_z, posterior_flow=self._posterior_flow)
  File "/media/harry/harry/ML/LSTM/OmniAnomaly/omni_anomaly/vae.py", line 362, in chain
    observed={'x': x}
  File "/usr/local/lib/python3.6/site-packages/tfsnippet/bayes.py", line 403, in variational_chain
    latent_axis=latent_axis,
  File "/usr/local/lib/python3.6/site-packages/tfsnippet/variational/chain.py", line 55, in __init__
    model.local_log_probs(iter(model)))
  File "/usr/local/lib/python3.6/site-packages/tfsnippet/bayes.py", line 297, in local_log_probs
    ret.append(self._stochastic_tensors[name].log_prob(name=ns))
  File "/usr/local/lib/python3.6/site-packages/tfsnippet/stochastic.py", line 156, in log_prob
    self.tensor, self.group_ndims, name=name)
  File "/media/harry/harry/ML/LSTM/OmniAnomaly/omni_anomaly/wrapper.py", line 75, in log_prob
    log_prob, _, _, _, _, _, _ = self._distribution.forward_filter(given)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_probability/python/distributions/linear_gaussian_ssm.py", line 716, in forward_filter
    initializer=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 724, in scan
    maximum_iterations=n)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3556, in while_loop
    return_same_structure)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3087, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3059, in _BuildLoop
    next_vars.append(_AddNextAndBackEdge(m, v))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 677, in _AddNextAndBackEdge
    _EnforceShapeInvariant(m, v)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 620, in _EnforceShapeInvariant
    "less-specific shape." % (input_t.name, input_t.shape, n_shape))
ValueError: Input tensor 'model/trainer/loss/training_loss/VAE.chain/VariationalChain/model_log_joint/z.log_prob/forward_filter/add:0' enters the loop with shape (?, 3, 1), but has shape (?, 3, ?) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.

```

**Comment by isenilov** [comment]
Might be a tf incompatibility. Faced it with tf > 1.12.x

**Comment by NiuChH** [comment]
We have confirmed that the code is compatible with TensorFlow 1.12.0, and updated it in `requirements.txt`. Please reinstall the dependencies accordingly. Sorry for the inconvenience. 
And thanks @isenilov !
