### ISSUE TITLE
Cannot install and run the code with tf2.9.3

### ISSUE THREAD

**Issue by xiaogangzhu** [smallcowbaby/OmniAnomaly#54]
Hi,

I saw your update on tf 2.9.3 compatible but I tried 
```
pip install -r requirement.txt
```
and it fails. So I remove the version of some package and it seems like tfsnippet has some problems with import
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tfsnippet/__init__.py", line 4, in <module>
    from . import (dataflows, datasets, distributions, evaluation, layers,
  File "/usr/local/lib/python3.8/dist-packages/tfsnippet/dataflows/__init__.py", line 1, in <module>
    from .array_flow import *
  File "/usr/local/lib/python3.8/dist-packages/tfsnippet/dataflows/array_flow.py", line 4, in <module>
    from tfsnippet.utils import minibatch_slices_iterator, generate_random_seed
  File "/usr/local/lib/python3.8/dist-packages/tfsnippet/utils/__init__.py", line 20, in <module>
    from .session import *
  File "/usr/local/lib/python3.8/dist-packages/tfsnippet/utils/session.py", line 71, in <module>
    def get_variables_as_dict(scope=None, collection=tf.GraphKeys.GLOBAL_VARIABLES):
AttributeError: module 'tensorflow' has no attribute 'GraphKeys'
```
Any solutions?

**Comment by LittleMonsterSen** [comment]
installing tensor flow 1.13.0 could help

**Comment by LittleMonsterSen** [comment]
But I think only version before 1.12.0 works for all the code. You may look at the issue #5

**Comment by xiaogangzhu** [comment]
Are you going to upgrade the code to tf2 version? If does it will be lots of help!

**Comment by simoneto** [comment]
I have the same problem. Has anyone found the solution?

**Comment by heMeyer** [comment]
It doesnt seem to be super easy to get the code running with tensorflow 2.x. Even when using something like

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

the code wont work. The problem besides the code itself is "tfsnippet" thats used quite a lot (more than 6 years old too).
One method to get the code running is using conda creating an env with the old library versions (as the istallation via pip also doesnt seem to work)

You can create the env using following environment.yml and conda:

name: env_omni_anomaly
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - six==1.11.0
  - matplotlib==3.0.2
  - numpy==1.15.4
  - pandas==0.23.4
  - scipy==1.2.0
  - scikit-learn==0.20.2
  - tqdm==4.28.1
  - imageio==2.4.1
  - fs==2.3.0
  - click==7.0
  - pip:
      - tensorflow-gpu==1.12.0
      - tensorflow-probability==0.5.0
      - git+https://github.com/thu-ml/zhusuan.git
      - git+https://github.com/haowen-xu/tfsnippet.git@v0.2.0-alpha1
